# Generated by Django 4.1.6 on 2023-02-17 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_catagory_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='produbt_name',
            new_name='product_name',
        ),
    ]
