# Generated by Django 4.1.7 on 2023-02-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('city', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=200)),
                ('property_type', models.CharField(max_length=50)),
                ('rent_amount', models.IntegerField()),
                ('status', models.CharField(max_length=25)),
                ('bond', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=200)),
                ('area', models.IntegerField()),
                ('about', models.CharField(max_length=100)),
                ('parking', models.CharField(max_length=10)),
                ('floor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RentedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('property_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('rating_id', models.IntegerField(primary_key=True, serialize=False)),
                ('property_id', models.IntegerField()),
                ('comments', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('timeperiod', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=10)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isOwner', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='photo',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
